### ISSUE TITLE
Update image in organization

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/.eclipsefdn#3]
In #1 I recently update the name of the Eclipse Project - the new logo is now ready (See https://github.com/eclipse-cdt-cloud/website/pull/39/files) but I don't know how to update that with otterdog.

This is the image I am talking about:

![image](https://github.com/eclipse-cdt-cloud/.eclipsefdn/assets/679236/ca0e2977-93aa-46f1-b975-2220734bac2d)

@netomi is it possible to update this image with otterdog?

@planger FYI

**Comment by netomi** [comment]
Unfortunately, this can not be changed by otterdog yet as there is no API from github to change the avatar of an organization account. I can change that manually ofc. It also should be changed at https://projects.eclipse.org/projects/ecd.cdt-cloud. Would you mind creating a HelpDesk ticket for that so that others are aware of that? I can pick it up.

**Comment by jonahgraham** [comment]
I asked @planger if he can handle it in https://github.com/eclipse-cdt-cloud/website/pull/39

**Comment by planger** [comment]
Please note that I opened [a PR](https://github.com/eclipse-cdt-cloud/cdt-cloud/pull/34) which adds the logo sources and files.

**Comment by planger** [comment]
Fyi, I've opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3334 and changed the logo at https://projects.eclipse.org/projects/ecd.cdt-cloud
